"""The zero-buy-in on-ramp: paperplot's look as a plain matplotlib style sheet.

``figure()``/``save()`` are the product — they size to the real column width,
embed fonts, and preflight. But the *look* (type scale, Okabe-Ito cycle, tick
style, full box) is just rcParams, and rcParams travel as ``.mplstyle`` files.

``export_mplstyle("aps")`` writes a style file; ``register_mplstyles()`` makes
``plt.style.use("paperplot-aps")`` work in-process. Either way a user gets the
styling with no API commitment, then graduates to ``pp.figure()`` for the part a
style sheet *cannot* do — true sizing and preflight.

We do NOT register on import: paperplot's first import stays silent and mutates
no global matplotlib state. Registration is an explicit opt-in.
"""

from __future__ import annotations

from typing import Optional

from cycler import Cycler

from .registry import available, get_spec
from .style import rcparams

# Journal keys exposed as style sheets. Variants (prl/prx/prb) share APS styling,
# so they'd produce identical sheets — we skip them here to keep the list clean.
_STYLE_KEYS = ("aps", "nature", "ieee", "talk")


def _format_value(key: str, value) -> str:
    """Serialize one rcParam value to matplotlib ``.mplstyle`` syntax."""
    if key == "axes.prop_cycle" and isinstance(value, Cycler):
        # '#' starts a comment in .mplstyle files, so hex colors are written
        # bare (no leading '#') — exactly how matplotlib's own matplotlibrc does.
        colors = (c.lstrip("#") for c in value.by_key().get("color", []))
        inner = ", ".join(f"'{c}'" for c in colors)
        return f"cycler('color', [{inner}])"
    if isinstance(value, bool):  # before int/float — bool is an int subclass
        return "True" if value else "False"
    if isinstance(value, (list, tuple)):
        return ", ".join(str(v) for v in value)
    return str(value)


def to_mplstyle_text(journal, *, serif: bool = False, usetex: bool = False,
                     palette=None, math: str = "cm",
                     font_scale: float = 1.0) -> str:
    """Render a journal's rcParams as ``.mplstyle`` file text.

    Accepts the same styling options as :func:`paperplot.use`. The result is the
    look only — it carries the journal's *default* (single-column) figure size,
    not per-figure sizing, which is what ``pp.figure(width=...)`` is for.
    """
    spec = get_spec(journal) if not hasattr(journal, "revision") else journal
    rc = rcparams(spec, serif=serif, usetex=usetex, palette=palette, math=math,
                  font_scale=font_scale)
    lines = [
        f"# paperplot style for {spec.name} (revision {spec.revision}).",
        "# Generated by paperplot.export_mplstyle — the look only.",
        "# For journal-true sizing, font embedding, and preflight, use pp.figure()/pp.save().",
        "",
    ]
    for key in sorted(rc):
        lines.append(f"{key}: {_format_value(key, rc[key])}")
    return "\n".join(lines) + "\n"


def export_mplstyle(journal, path: Optional[str] = None, **opts) -> str:
    """Write (and return) a ``.mplstyle`` file for ``journal``.

    With no ``path``, returns the text without writing. Pass styling options
    (``serif``, ``usetex``, ``palette``, ``math``, ``font_scale``) just like
    :func:`paperplot.use`.
    """
    text = to_mplstyle_text(journal, **opts)
    if path is not None:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
    return text


def register_mplstyles() -> list[str]:
    """Register ``paperplot-<journal>`` styles into matplotlib's style library.

    After calling this, ``plt.style.use("paperplot-aps")`` works (and the names
    appear in ``plt.style.available``). Opt-in — paperplot never does this on
    import. Returns the registered style names.
    """
    import matplotlib.style as mstyle

    names = []
    known = set(available())
    for key in _STYLE_KEYS:
        if key not in known:
            continue
        spec = get_spec(key)
        name = f"paperplot-{key}"
        # Library entries are applied via rcParams.update, so the live dict
        # (cycler object intact) works directly — no text round-trip needed.
        mstyle.library[name] = rcparams(spec)
        names.append(name)
    mstyle.available[:] = sorted(mstyle.library)
    return names
